server:
  port: 8079

spring:
  application:
    name: pdda-public-display-manager
  config:
    import: "optional:configtree:/mnt/secrets/pdda/"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:pdda}${DB_OPTIONS:}
    username: ${DB_USER_NAME:postgres}
    password: ${DB_PASSWORD:password}
    schema: ${DB_SCHEMA:pdda}
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: pdda
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoint:
    health:
      show-details: "always"
      # group:
      #  readiness:
      #   include: "db"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
