java:
  applicationPort: 5432
  image: 'sdshmctspublic.azurecr.io/pdm/public-display-manager:latest'
  environment:
    A_KEY: 'a value'
  keyVaults:
    "pdda":
      secrets:
        - name: public-display-data-aggregator-POSTGRES-USER
          alias: DB_USER_NAME
        - name: public-display-data-aggregator-POSTGRES-PASS
          alias: DB_PASSWORD
        - name: public-display-data-aggregator-POSTGRES-DATABASE
          alias: DB_NAME
        - name: public-display-data-aggregator-POSTGRES-HOST
          alias: DB_HOST
        - name: public-display-data-aggregator-POSTGRES-PORT
          alias: DB_PORT