java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    STAGING: "true"
    RUN_DB_MIGRATION_ON_STARTUP: true
    POSTGRES_USER: "{{ .Values.postgresql.auth.username }}"