java:
  applicationPort: 8080
  readinessPath: '/pmd/health'
  livenessPath: '/pdm/health'
  startupPath: '/pdm/health'
  image: 'sdshmctspublic.azurecr.io/pdm/public-display-manager:latest'
  ingressHost: pdm-public-display-manager.{{ .Values.global.environment }}.platform.hmcts.net
  keyVaults:
    "pdda":
      secrets:
        - name: public-display-data-aggregator-POSTGRES-USER
          alias: DB_USER_NAME
        - name: public-display-data-aggregator-POSTGRES-PASS
          alias: DB_PASSWORD
        - name: public-display-data-aggregator-POSTGRES-DATABASE
          alias: DB_NAME
        - name: public-display-data-aggregator-POSTGRES-HOST
          alias: DB_HOST
        - name: public-display-data-aggregator-POSTGRES-PORT
          alias: DB_PORT
        - name: public-display-data-aggregator-POSTGRES-SCHEMA
          alias: DB_SCHEMA
        - name: app-insights-connection-string-pdm
          alias: app-insights-connection-string-pdm
  environment:
    RUN_DB_MIGRATION_ON_STARTUP: false